/**
 * Regenerates docs/feature-map.md and the marked section of README.md from tools/plan.json and
 * docs/phase-status.json.
 *
 *   bun run tools/feature-map.ts                          rewrite both files
 *   bun run tools/feature-map.ts --phase 1 --status shipped
 */
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs"
import { parseArgs } from "node:util"

type Plan = typeof import("./plan.json")
const plan: Plan = JSON.parse(readFileSync(new URL("./plan.json", import.meta.url), "utf8"))

const DOCS = new URL("../docs/", import.meta.url)
const STATUS_PATH = new URL("phase-status.json", DOCS)
mkdirSync(DOCS, { recursive: true })

const STATUS_LABEL = {
  planned: "planned",
  building: "in progress",
  shipped: "shipped",
} as const

type PhaseStatus = Record<string, keyof typeof STATUS_LABEL>
const status: PhaseStatus = existsSync(STATUS_PATH) ? JSON.parse(readFileSync(STATUS_PATH, "utf8")) : {}

/** Epic issue per phase, from `tools/issues/create.ts`. */
const ISSUES: Record<string, number> = {
  "Phase 1": 3,
  "Phase 2": 9,
  "Phase 3": 14,
  "Phase 4": 19,
  "Phase 5": 24,
  "Phase 6": 29,
  "Phase 7": 34,
  "Phase 8": 39,
  "Phase 9": 45,
}

const options = parseArgs({
  args: Bun.argv.slice(2),
  options: {
    phase: { type: "string" },
    status: { type: "string" },
  },
  strict: true,
}).values

if (options.phase && options.status) {
  status[options.phase] = options.status as keyof typeof STATUS_LABEL
  writeFileSync(STATUS_PATH, `${JSON.stringify(status, null, 2)}\n`)
}

const rows = [
  "| Phase | Focus | Commits | Status | Issue |",
  "| --- | --- | --- | --- | --- |",
  ...plan.phases.map((phase) => {
    const state = status[`Phase ${phase.id}`] ?? "planned"
    const commits = phase.commits.map((commit) => commit.id).join(", ")
    return `| ${phase.id}. ${phase.title} | ${phase.focus} | ${commits} | ${STATUS_LABEL[state]} | #${ISSUES[`Phase ${phase.id}`]} |`
  }),
]

const header = [
  "# Feature map",
  "",
  "Generated by `tools/feature-map.ts` from `tools/plan.json`. One row per phase of the build plan, one",
  "sub-issue per commit. Update a phase with `bun run tools/feature-map.ts --phase <n> --status shipped`.",
  "",
]

writeFileSync(new URL("feature-map.md", DOCS), `${header.join("\n")}\n${rows.join("\n")}\n`)

const readmePath = new URL("../README.md", import.meta.url)
if (existsSync(readmePath)) {
  const readme = readFileSync(readmePath, "utf8")
  const start = "<!-- FEATURE-MAP:START -->"
  const end = "<!-- FEATURE-MAP:END -->"
  if (readme.includes(start) && readme.includes(end)) {
    writeFileSync(readmePath, readme.replace(new RegExp(`${start}[\\s\\S]*${end}`), `${start}\n\n${rows.join("\n")}\n\n${end}`))
  }
}

console.log(`feature map rewritten (${plan.phases.length} phases)`)
