/**
 * Regenerates the feature map in docs/feature-map.md and the marked section of README.md from
 * tools/plan.json, the issue table, and the per-phase status file.
 *
 *   bun run tools/feature-map.ts            rewrite both files
 *   bun run tools/feature-map.ts --phase 1 --status shipped
 */
import { existsSync, readFileSync, writeFileSync } from "node:fs"
import { parseArgs } from "node:util"

type Plan = typeof import("./plan.json")
const plan: Plan = JSON.parse(readFileSync(new URL("./plan.json", import.meta.url), "utf8"))

const STATUS_PATH = new URL("../docs/phase-status.json", import.meta.url)
const FEATURE_MAP_PATH = new URL("../docs/feature-map.md", import.meta.url)
const README_PATH = new URL("../README.md", import.meta.url)
const OVERVIEW_PATH = new URL("../orchestrate/nightcode/overview.md", import.meta.url)

type PhaseStatus = Record<string, "planned" | "building" | "shipped">
const status: PhaseStatus = existsSync(STATUS_PATH) ? JSON.parse(readFileSync(STATUS_PATH, "utf8")) : {}

const options = parseArgs({
  args: Bun.argv,
  options: {
    phase: { type: "string" },
    status: { type: "string" },
  },
  strict: true,
}).values

if (options.phase && options.status) {
  status[options.phase] = options.status as PhaseStatus[string]
  writeFileSync(STATUS_PATH, `${JSON.stringify(status, null, 2)}\n`)
}

function issueNumber(title: string): string {
  if (!existsSync(OVERVIEW_PATH)) return ""
  const row = readFileSync(OVERVIEW_PATH, "utf8")
    .split("\n")
    .find((line) => line.includes(`| ${title} |`))
  const match = row?.match(/#(\d+)/)
  return match ? `#${match[1]}` : ""
}

const STATUS_LABEL: Record<PhaseStatus[string], string> = {
  planned: "planned",
  building: "in progress",
  shipped: "shipped",
}

const rows: string[] = ["| Phase | Focus | Commits | Status | Issue |", "| --- | --- | --- | --- | --- |"]
for (const phase of plan.phases) {
  const state = status[String(phase.id)] ?? "planned"
  const commits = phase.commits.map((commit) => commit.id).join(", ")
  rows.push(`| ${phase.id}. ${phase.title} | ${phase.focus} | ${commits} | ${STATUS_LABEL[state]} | ${issueNumber(`Phase ${phase.id}`)} |`)
}

const body = [
  "# Feature map",
  "",
  "Generated by `tools/feature-map.ts` from `tools/plan.json`. One row per phase of the build plan,",
  "one sub-issue per commit. Update a phase with `bun run tools/feature-map.ts --phase <n> --status shipped`.",
  "",
  ...rows,
  "",
]

writeFileSync(FEATURE_MAP_PATH, body.join("\n"))

if (existsSync(README_PATH)) {
  const readme = readFileSync(README_PATH, "utf8")
  const start = "<!-- FEATURE-MAP:START -->"
  const end = "<!-- FEATURE-MAP:END -->"
  if (readme.includes(start) && readme.includes(end)) {
    const section = `${start}\n\n${rows.join("\n")}\n\n${end}`
    const pattern = new RegExp(`${start}[\\s\\S]*${end}`)
    writeFileSync(README_PATH, readme.replace(pattern, section))
  }
}

console.log(`feature map rewritten (${plan.phases.length} phases)`)
